<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: 
The entry points for the data into the neural network. These are the nerons that first touch and process the input data.
### Hidden Layer:
These are neurons that take the output of a previous neurons and use that output as they're input. These neurons never handle or process the data directly.
### Output Layer:
These are nuerons that process the work done by the other layers and give a meaningful, interpretable result.

### Neuron:
At it's heart, little more than a mathematical function. It takes an input, runs it through a certain number of calculations, and gives an output.
### Weight:
Once a layer has finished its process and passes the data onto the next layer, weights tell the next layer how important each bit of processed data is.
### Activation Function:
Some neurons aren't always run every time a neural network processes data. Conditions under which certain neurons which would normally be unrun will actually be run are activation functions.
### Node Map:
The overall architecture of a neural network. How many layers there are, how many nodes per layer, etc. 
### Perceptron:
The simplest kind of neural network. It consits of one input node that takes as many inputs as you desire, runs some computations on those inputs, and then will return an output.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

Data enters the input layer nodes and the input layer nodes process the data. It does this by running all nodes whose activation functions are met. Once all activated nodes are run the data is sent to the next layer. On the way, as the data goes from the input layer to the first hidden layer two things happen: the weight of the connection is applied and bias is added (IN THAT ORDER). This process repeats for all remaining non-output layers. 1) run all activated nodes whose activation functions are satisfied, 2) adjust the output of these activated nodes by first the weight of the connection and then the bias of the layer, and 3) send the finished process to the next layer. Once that is done for all non-output layer layers, the output layer takes the data it receives and processses it, after which the results will be an output that can be applied to the data i.e the output is meaningful in the context of the problem, there is no further processing that needs to be done to reveal the meaning of the output.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [199]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'bias': [1,1,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')
df.head()

x1  x2  bias  y
0   0   0     1  1
1   1   0     1  1
2   0   1     1  1
3   1   1     1  0

In [200]:
import numpy as np

def sigmoid(x):
    return (1 / (1 + np.exp(-x)))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1 - sx)
    
def sigmoid_derivative2(x):
    return (np.exp(-x) * sigmoid(x)**2)

In [201]:
sigmoid(-50), sigmoid(0), sigmoid(50)

(1.928749847963918e-22, 0.5, 1.0)

In [202]:
# get our inputs and output from the dataframe
inputs = df.to_numpy()

output_badshape = df.iloc[:4, -1].to_numpy()
correct_output = []
for i in output_badshape:
    correct_output.append([i])
correct_output = np.array(correct_output)


print(inputs, "\n\n", correct_output)

[[0 0 1 1]
 [1 0 1 1]
 [0 1 1 1]
 [1 1 1 0]] 

 [[1]
 [1]
 [1]
 [0]]


In [203]:
# make weights
from numpy import random

# gets a list of numbers from -1 to 1
# we have 2 input vectors, so we need 2 weights
weights = 2 * random.random_sample((4,1)) - 1
weights

array([[ 0.56579051],
       [-0.18044911],
       [ 0.44639235],
       [ 0.35327997]])

In [204]:
# apply weights
# we want a 4x1 at the end of this dot product. 
# inputs a 4x2, weights is a 2x1 so the desired (and only valid) order for the dot product is:
# inputs x weights
weighted_data = np.dot(inputs, weights)
weighted_data

array([[0.79967232],
       [1.36546283],
       [0.61922321],
       [0.83173375]])

In [205]:
# act on weighted data by sigmoid function
activated_data = sigmoid(weighted_data)
activated_data

array([[0.68990438],
       [0.79664612],
       [0.65004186],
       [0.6967214 ]])

In [206]:
error = correct_output - activated_data
error

array([[ 0.31009562],
       [ 0.20335388],
       [ 0.34995814],
       [-0.6967214 ]])

In [207]:
adjusted_error = error * sigmoid_derivative(activated_data)
adjusted_error

array([[ 0.0689845 ],
       [ 0.04355473],
       [ 0.07886123],
       [-0.15464219]])

In [208]:
# inputs 4x2, adjadjusted_error 4x1, 
# inputs.T 2x4
# valid product: inputs.T dot adjusted_error

weights += np.dot(inputs.T, adjusted_error)
weights

array([[ 0.45470305],
       [-0.25623007],
       [ 0.48315062],
       [ 0.54468044]])

In [212]:
### every step in one, done a bunch of times

# make random weights from -1 to 1
weights = 2 * random.random_sample((4,1)) - 1

for i in range(10000):
    # apply weights to input data
    weighted_data = np.dot(inputs, weights)
    # apply node to weighted data
    activated_data = sigmoid(weighted_data)
    # calculate error
    error = correct_output - activated_data
    # calculate necessary adjustments to the weights
    weight_adjustment = error * sigmoid_derivative(activated_data)
    # apply weight adjustment to weights
    weights += np.dot(inputs.T, weight_adjustment)

print("Weights: \n", weights)
print("\n Output: \n", activated_data)
print("\n Desired Output: \n", correct_output)
print("\n Error: \n", correct_output - activated_data)

Weights: 
 [[-4.60758221]
 [-4.62642329]
 [ 1.6553721 ]
 [10.89186664]]

 Output: 
 [[9.99996445e-01]
 [9.99643763e-01]
 [9.99636989e-01]
 [5.11049111e-04]]

 Desired Output: 
 [[1]
 [1]
 [1]
 [0]]

 Error: 
 [[ 3.55524781e-06]
 [ 3.56237100e-04]
 [ 3.63010647e-04]
 [-5.11049111e-04]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [213]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [224]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

features = list(diabetes)[:-1]

target = list(diabetes)[-1]

features, target

(['Pregnancies',
  'Glucose',
  'BloodPressure',
  'SkinThickness',
  'Insulin',
  'BMI',
  'DiabetesPedigreeFunction',
  'Age'],
 'Outcome')

In [232]:
diabetes.shape

(768, 9)

In [253]:
# train/test split
train = diabetes.iloc[:-100]
test = diabetes.iloc[:-101:-1]

In [263]:
# checks to make sure it was done correctly
train.shape, test.shape

((668, 9), (100, 9))

In [256]:
train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [257]:
test.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
767            1       93             70             31        0  30.4   
766            1      126             60              0        0  30.1   
765            5      121             72             23      112  26.2   
764            2      122             70             27        0  36.8   
763           10      101             76             48      180  32.9   

     DiabetesPedigreeFunction  Age  Outcome  
767                     0.315   23        0  
766                     0.349   47        1  
765                     0.245   30        0  
764                     0.340   27        0  
763                     0.171   63        0

In [258]:
# seperate features from the target

X_train = train[features]
y_train = train[target]

X_test = test[features]
y_test = test[target]

In [259]:
X_train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [260]:
y_train.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [411]:
##### Update this Class #####
import numpy as np

class Perceptron(object):
    
    def __init__(self, num_inputs, niter = 10):
        self.niter = niter
        self.num_inputs = num_inputs
        # Randomly Initialize Weights
        self.weights = np.array(2 * random.random_sample((self.num_inputs, 1)) - 1).reshape(self.num_inputs, 1)
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sigx = self.__sigmoid(x)
        return sigx * (1 - sigx)

    def fit(self, X, y):
        """
        Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """ 
        for i in range(self.niter):
            for X_i, y_i in zip(X, y):
                # create prediction
                prediction = self.predict(X_i)
                # measure error of prediction
                error = y_i - prediction
                # find proper weight adjustment based on error
                weight_adjustment = error * self.__sigmoid_derivative(X_i)
                weight_adjustment = weight_adjustment.reshape(self.num_inputs, 1)
#                     weight_adjustment.append([i])
                # apply the weight adjustment to the weights
                self.weights += weight_adjustment


#         # apply node to weighted data
#         activated_data = sigmoid(weighted_data)
#         # calculate error
#         error = correct_output - activated_data
#         # calculate necessary adjustments to the weights
#         weight_adjustment = error * sigmoid_derivative(activated_data)
#         # apply weight adjustment to weights
#         weights += np.dot(inputs.T, weight_adjustment)

    def predict(self, X):
        """Return class label after unit step"""
        # apply weights to input data
        weighted_data = np.dot(X, self.weights)
        # get sigmoid distribution
        activated_data = self.__sigmoid(weighted_data)
        return activated_data

In [412]:
node = Perceptron(len(features), niter=10000)

In [413]:
node.weights

array([[-0.56987618],
       [ 0.39689466],
       [ 0.40347117],
       [-0.53136639],
       [ 0.06688135],
       [ 0.62137996],
       [ 0.74430857],
       [-0.20392644]])

In [414]:
node.fit(X_train.to_numpy(), y_train.to_numpy());

//anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/ipykernel_launcher.py:13: RuntimeWarning: overflow encountered in exp
  del sys.path[0]


KeyboardInterrupt: 

In [448]:
def perceptron(X, y, niter=100000):
    num_feats = X.shape[1]
    y = y.reshape(X.shape[0], 1)
    weights = 2 * random.random_sample((num_feats, 1)) - 1
    weights = np.array(weights).reshape(num_feats, 1)
    
    print("X shape: ", X.shape, "\n Weights shape: ", weights.shape)
    for i in range(10000):
        # apply weights to input data
        weighted_data = np.dot(X, weights)
        print("weighted_data \n", weighted_data.shape)
        # apply node to weighted data
        activated_data = sigmoid(weighted_data)
        print("activated_data \n", activated_data.shape)
        # calculate error
        error = y - activated_data
        print("error \n", error.shape)
        # calculate necessary adjustments to the weights
        weight_adjustment = error * sigmoid_derivative(activated_data)
        print("weight_adj \n", weight_adjustment.shape)
        # apply weight adjustment to weights
        weights += np.dot(X.T, weight_adjustment)
        print("weights \n", weights.shape)
    
    return(weights, activated_data)

In [449]:
weights_perc, data_perc = perceptron(X_train.to_numpy(), y_train.to_numpy(), niter=100000)

X shape:  (668, 8) 
 Weights shape:  (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 

//anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: overflow encountered in exp
  after removing the cwd from sys.path.


(668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
error 
 (668, 1)
weight_adj 
 (668, 1)
weights 
 (8, 1)
weighted_data 
 (668, 1)
activated_data 
 (668, 1)
er

KeyboardInterrupt: 

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?